# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\marco\Downloads\ray-tracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\marco\Downloads\ray-tracer\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\marco\Downloads\ray-tracer\build\CMakeFiles C:\Users\marco\Downloads\ray-tracer\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\marco\Downloads\ray-tracer\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rt3

# Build rule for target.
rt3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 rt3
.PHONY : rt3

# fast build rule for target.
rt3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/build
.PHONY : rt3/fast

libs/lodepng/lodepng.obj: libs/lodepng/lodepng.cpp.obj
.PHONY : libs/lodepng/lodepng.obj

# target to build an object file
libs/lodepng/lodepng.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/libs/lodepng/lodepng.cpp.obj
.PHONY : libs/lodepng/lodepng.cpp.obj

libs/lodepng/lodepng.i: libs/lodepng/lodepng.cpp.i
.PHONY : libs/lodepng/lodepng.i

# target to preprocess a source file
libs/lodepng/lodepng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/libs/lodepng/lodepng.cpp.i
.PHONY : libs/lodepng/lodepng.cpp.i

libs/lodepng/lodepng.s: libs/lodepng/lodepng.cpp.s
.PHONY : libs/lodepng/lodepng.s

# target to generate assembly for a file
libs/lodepng/lodepng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/libs/lodepng/lodepng.cpp.s
.PHONY : libs/lodepng/lodepng.cpp.s

libs/math/math.obj: libs/math/math.cpp.obj
.PHONY : libs/math/math.obj

# target to build an object file
libs/math/math.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/libs/math/math.cpp.obj
.PHONY : libs/math/math.cpp.obj

libs/math/math.i: libs/math/math.cpp.i
.PHONY : libs/math/math.i

# target to preprocess a source file
libs/math/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/libs/math/math.cpp.i
.PHONY : libs/math/math.cpp.i

libs/math/math.s: libs/math/math.cpp.s
.PHONY : libs/math/math.s

# target to generate assembly for a file
libs/math/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/libs/math/math.cpp.s
.PHONY : libs/math/math.cpp.s

libs/tinyxml2/tinyxml2.obj: libs/tinyxml2/tinyxml2.cpp.obj
.PHONY : libs/tinyxml2/tinyxml2.obj

# target to build an object file
libs/tinyxml2/tinyxml2.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/libs/tinyxml2/tinyxml2.cpp.obj
.PHONY : libs/tinyxml2/tinyxml2.cpp.obj

libs/tinyxml2/tinyxml2.i: libs/tinyxml2/tinyxml2.cpp.i
.PHONY : libs/tinyxml2/tinyxml2.i

# target to preprocess a source file
libs/tinyxml2/tinyxml2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/libs/tinyxml2/tinyxml2.cpp.i
.PHONY : libs/tinyxml2/tinyxml2.cpp.i

libs/tinyxml2/tinyxml2.s: libs/tinyxml2/tinyxml2.cpp.s
.PHONY : libs/tinyxml2/tinyxml2.s

# target to generate assembly for a file
libs/tinyxml2/tinyxml2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/libs/tinyxml2/tinyxml2.cpp.s
.PHONY : libs/tinyxml2/tinyxml2.cpp.s

source/app.obj: source/app.cpp.obj
.PHONY : source/app.obj

# target to build an object file
source/app.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/app.cpp.obj
.PHONY : source/app.cpp.obj

source/app.i: source/app.cpp.i
.PHONY : source/app.i

# target to preprocess a source file
source/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/app.cpp.i
.PHONY : source/app.cpp.i

source/app.s: source/app.cpp.s
.PHONY : source/app.s

# target to generate assembly for a file
source/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/app.cpp.s
.PHONY : source/app.cpp.s

source/main.obj: source/main.cpp.obj
.PHONY : source/main.obj

# target to build an object file
source/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/main.cpp.obj
.PHONY : source/main.cpp.obj

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/parser.obj: source/parser.cpp.obj
.PHONY : source/parser.obj

# target to build an object file
source/parser.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/parser.cpp.obj
.PHONY : source/parser.cpp.obj

source/parser.i: source/parser.cpp.i
.PHONY : source/parser.i

# target to preprocess a source file
source/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/parser.cpp.i
.PHONY : source/parser.cpp.i

source/parser.s: source/parser.cpp.s
.PHONY : source/parser.s

# target to generate assembly for a file
source/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/parser.cpp.s
.PHONY : source/parser.cpp.s

source/sphere.obj: source/sphere.cpp.obj
.PHONY : source/sphere.obj

# target to build an object file
source/sphere.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/sphere.cpp.obj
.PHONY : source/sphere.cpp.obj

source/sphere.i: source/sphere.cpp.i
.PHONY : source/sphere.i

# target to preprocess a source file
source/sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/sphere.cpp.i
.PHONY : source/sphere.cpp.i

source/sphere.s: source/sphere.cpp.s
.PHONY : source/sphere.s

# target to generate assembly for a file
source/sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\rt3.dir\build.make CMakeFiles/rt3.dir/source/sphere.cpp.s
.PHONY : source/sphere.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... rt3
	@echo ... libs/lodepng/lodepng.obj
	@echo ... libs/lodepng/lodepng.i
	@echo ... libs/lodepng/lodepng.s
	@echo ... libs/math/math.obj
	@echo ... libs/math/math.i
	@echo ... libs/math/math.s
	@echo ... libs/tinyxml2/tinyxml2.obj
	@echo ... libs/tinyxml2/tinyxml2.i
	@echo ... libs/tinyxml2/tinyxml2.s
	@echo ... source/app.obj
	@echo ... source/app.i
	@echo ... source/app.s
	@echo ... source/main.obj
	@echo ... source/main.i
	@echo ... source/main.s
	@echo ... source/parser.obj
	@echo ... source/parser.i
	@echo ... source/parser.s
	@echo ... source/sphere.obj
	@echo ... source/sphere.i
	@echo ... source/sphere.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

